dict_estacion_linea = { "RioSeco" : ("Azul"),
                        "UPEA" : ("Azul"),
                        "PzaLaPaz" : ("Azul"),
                        "PzaLaLibertad": ("Azul"),
                        "16deJulio" : ("Azul", "Roja"),
                        "Cementerio" : ("Roja"),
                        "Central" : ("Roja", "Naranja"),
                        "Armentia" : ("Naranja"),
                        "Periferica" : ("Naranja"),
                        "Villarroel" : ("Naranja", "Blanco"),
                        "Busch" : ("Blanco", "Cafe"),
                        "LasVillas" : ("Cafe"),
                        "Triangular" : ("Blanco"),
                        "DelPoeta" : ("Celeste","Blanco"),
                        "TeatroAlAireLibre" : ("Celeste"),
                        "Prado" : ("Celeste"),
                        "Libertador" : ("Celeste", "Verde", "Amarillo"),
                        "AltoObrajes" : ("Verde"),
                        "Obrajes" : ("Verde"),
                        "Irpavi" : ("Verde"),
                        "Sopocachi" : ("Amarillo"),
                        "BuenosAires" : ("Amarillo"),
                        "Mirador" : ("Amarillo",  "Plateado"),
                        "FaroMurillo" : ("Plateado", "Morado"),
                        "Obelisco" : ("Morado"),
                        "6deMarzo" : ("Morado")
                        }

print(dict_estacion_linea["16deJulio"][0])
